x-clickhouse-defaults: &clickhouse-defaults
  image: clickhouse/clickhouse-server:25.12.9
  tty: true
  restart: unless-stopped
  logging:
    options:
      max-size: 50m
      max-file: "10"
  healthcheck:
    test:
      - CMD
      - wget
      - --spider
      - -q
      - 0.0.0.0:8123/ping
    interval: 30s
    timeout: 5s
    retries: 3
  ulimits:
    nproc: 65535
    nofile:
      soft: 262144
      hard: 262144

x-zookeeper-defaults: &zookeeper-defaults
  image: signoz/zookeeper:3.9.3
  restart: unless-stopped
  logging:
    options:
      max-size: 50m
      max-file: "10"
  healthcheck:
    test:
      - CMD-SHELL
      - curl -s -m 2 http://localhost:8080/commands/ruok | grep error | grep null
    interval: 30s
    timeout: 5s
    retries: 3

services:
  zookeeper:
    <<: *zookeeper-defaults
    container_name: signoz-zookeeper
    user: root
    environment:
      - ZOO_SERVER_ID=1
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_AUTOPURGE_INTERVAL=1
      - ZOO_ENABLE_PROMETHEUS_METRICS=yes
      - ZOO_PROMETHEUS_METRICS_PORT_NUMBER=9141

  clickhouse:
    <<: *clickhouse-defaults
    container_name: signoz-clickhouse
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1

  signoz-telemetrystore-migrator:
    image: signoz/signoz-otel-collector:v0.144.2
    container_name: signoz-telemetrystore-migrator
    restart: on-failure
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        /signoz-otel-collector migrate bootstrap &&
        /signoz-otel-collector migrate sync up &&
        /signoz-otel-collector migrate async up
    environment:
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_DSN=tcp://clickhouse:9000
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_CLUSTER=cluster
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_REPLICATION=true
      - SIGNOZ_OTEL_COLLECTOR_TIMEOUT=10m
    depends_on:
      clickhouse:
        condition: service_healthy
    logging:
      options:
        max-size: 50m
        max-file: "10"

  signoz:
    image: signoz/signoz:v0.117.1
    container_name: signoz
    restart: unless-stopped
    command:
      - --config=/root/config/prometheus.yml
    environment:
      - SIGNOZ_ALERTMANAGER_PROVIDER=signoz
      - SIGNOZ_TELEMETRYSTORE_CLICKHOUSE_DSN=tcp://clickhouse:9000
      - SIGNOZ_SQLSTORE_SQLITE_PATH=/var/lib/signoz/signoz.db
      - SIGNOZ_TOKENIZER_JWT_SECRET=secret
    depends_on:
      clickhouse:
        condition: service_healthy
      signoz-telemetrystore-migrator:
        condition: service_completed_successfully
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - -q
        - localhost:8080/api/v1/health
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      options:
        max-size: 50m
        max-file: "10"

  otel-collector:
    image: signoz/signoz-otel-collector:v0.144.2
    container_name: signoz-otel-collector
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        /signoz-otel-collector migrate sync check &&
        /signoz-otel-collector --config=/etc/otel-collector-config.yaml --manager-config=/etc/manager-config.yaml --copy-path=/var/tmp/collector-config.yaml
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=host.name=signoz-host,os.type=linux
      - LOW_CARDINAL_EXCEPTION_GROUPING=false
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_DSN=tcp://clickhouse:9000
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_CLUSTER=cluster
      - SIGNOZ_OTEL_COLLECTOR_CLICKHOUSE_REPLICATION=true
      - SIGNOZ_OTEL_COLLECTOR_TIMEOUT=10m
    depends_on:
      clickhouse:
        condition: service_healthy
      signoz:
        condition: service_healthy
      signoz-telemetrystore-migrator:
        condition: service_completed_successfully
    logging:
      options:
        max-size: 50m
        max-file: "10"
