kind: pipeline
type: docker
name: production-docker-pipeline

environment:
  IMAGE_NAME: docker-registry.acovado.club/production-image

steps:
  - name: debug-environment
    image: alpine
    commands:
      - echo "IMAGE_NAME=${IMAGE_NAME}"
      - echo "DRONE_COMMIT_SHA=${DRONE_COMMIT_SHA}"

  - name: build-image
    image: docker:20
    environment:
      DOCKER_BUILDKIT: 1
    commands:
      - docker build --target production -t ${IMAGE_NAME}:${DRONE_COMMIT_SHA} .

  - name: tag-latest
    image: docker:20
    commands:
      - docker tag ${IMAGE_NAME}:${DRONE_COMMIT_SHA} ${IMAGE_NAME}:latest

  - name: push-images
    image: docker:20
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    commands:
      - echo "$DOCKER_PASSWORD" | docker login docker-registry.acovado.club -u "$DOCKER_USERNAME" --password-stdin
      - docker push ${IMAGE_NAME}:${DRONE_COMMIT_SHA}
      - docker push ${IMAGE_NAME}:latest

trigger:
  branch:
    - ci/setup
