kind: pipeline
type: docker
name: docker-pipeline

environment:
  REGISTRY_URL: docker-registry.acovado.club
  IMAGE_NAME: docker-registry.acovado.club/test-image

volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock

steps:
  ##############################################################################
  # Build and push the image
  ##############################################################################

  - name: build-image
    image: docker:20
    environment:
      DOCKER_BUILDKIT: 1
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock
    commands:
      - docker build --target production -t $${IMAGE_NAME}:${DRONE_COMMIT_SHA} .
      - docker tag $${IMAGE_NAME}:${DRONE_COMMIT_SHA} $${IMAGE_NAME}:latest

  - name: push-image
    image: docker:20
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock
    commands:
      - echo "$DOCKER_PASSWORD" | docker login $${REGISTRY_URL} -u "$DOCKER_USERNAME" --password-stdin
      - docker push $${IMAGE_NAME}:${DRONE_COMMIT_SHA}
      - docker push $${IMAGE_NAME}:latest

trigger:
  branch:
    - ci/setup
