version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      log_min_messages: warning
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U development']
      interval: 10s
      timeout: 5s
      retries: 5
