version: '3.8'

services:
  postgres:
    extends:
      file: ./docker-compose.base.yaml
      service: postgres
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
      POSTGRES_DB: development
    ports:
      - '5432:5432'
