version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
      POSTGRES_DB: development
      log_min_messages: warning
    ports:
      - '5432:5432'
    networks:
      - private_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U development']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  private_network:
    name: private_network
