version: '3.8'

services:
  metabase-db:
    image: postgres:15
    container_name: metabase-db
    environment:
      POSTGRES_USER: metabase_user
      POSTGRES_PASSWORD: metabase_pass
      POSTGRES_DB: metabase_db
    volumes:
      - metabase-db-data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_db
      MB_DB_PORT: 5432
      MB_DB_USER: metabase_user
      MB_DB_PASS: metabase_pass
      MB_DB_HOST: metabase-db
    ports:
      - '${METABASE_PORT}:3000'
    depends_on:
      - metabase-db
    volumes:
      - metabase-data:/metabase-data

volumes:
  metabase-db-data:
  metabase-data:
