services:
  bebe:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: bebe
    working_dir: /usr/src/app
    command:
      ['bunx', 'turbo', 'run', 'dev', '--filter=@modules/*', '--filter=...@apps/bebe']
    ports:
      - '6000:3000'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - apps/bebe/.env
