version: '3.9'
services:
  grafana:
    image: grafana/grafana:10.1.1
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - 3000:3000
    depends_on:
      - tempo
      - prometheus

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ['--config=/etc/otel-collector-config.yaml']
    ports:
      - '4317:4317' # OTLP gRPC receiver
      - '4318:4318' # OTLP gRPC receiver

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [-config.file=/etc/tempo.yaml]
    ports:
      - '3200:3200'

volumes:
  grafana-data:
  tempo-data:
