receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:

extensions:
  health_check: {}

exporters:
  tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  prometheus:
    endpoint: '0.0.0.0:9090'

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [tempo]
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
