version: '3.8'

services:
  rabbitmq:
    extends:
      file: ./docker-compose.base.yaml
      service: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    ports:
      - '5672:5672' # Port for RabbitMQ communication
      - '15672:15672' # Management UI port
